# Generated by Django 5.2.6 on 2025-09-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('skill_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=15)),
                ('career_stage', models.CharField(blank=True, choices=[('student', 'Student'), ('entry_level', 'Entry Level'), ('mid_level', 'Mid Level'), ('senior_level', 'Senior Level'), ('executive', 'Executive'), ('career_changer', 'Career Changer'), ('freelancer', 'Freelancer')], max_length=20)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('marketing', 'Marketing'), ('design', 'Design'), ('sales', 'Sales'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('startup', 'Startup'), ('non_profit', 'Non-Profit'), ('government', 'Government'), ('other', 'Other')], max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('learning_goals', models.TextField(blank=True, max_length=1000)),
                ('mentorship_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('not_available', 'Not Available'), ('on_break', 'On Break')], default='not_available', max_length=15)),
                ('mentorship_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for mentorship in USD', max_digits=8, null=True)),
                ('mentorship_bio', models.TextField(blank=True, help_text='Describe your mentoring style and expertise', max_length=1000)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
