# Generated by Django 5.2.6 on 2025-09-17 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('basic_info', 'Basic Information'), ('industry_selection', 'Industry Selection'), ('goals_setup', 'Learning Goals Setup'), ('preferences', 'Preferences'), ('complete', 'Complete')], default='welcome', max_length=20),
        ),
        migrations.CreateModel(
            name='UserIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('marketing', 'Marketing'), ('design', 'Design'), ('sales', 'Sales'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('startup', 'Startup'), ('non_profit', 'Non-Profit'), ('government', 'Government'), ('other', 'Other')], max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary industry for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_industries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Industry',
                'verbose_name_plural': 'User Industries',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('user', 'industry')},
            },
        ),
        migrations.CreateModel(
            name='UserLearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='Name of the skill or learning goal', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what you want to learn', max_length=500)),
                ('target_skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=15)),
                ('current_skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=15)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=15)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Progress completion percentage (0-100)')),
                ('ai_roadmap_id', models.CharField(blank=True, help_text='MongoDB document ID for AI-generated roadmap', max_length=100, null=True)),
                ('roadmap_generated_at', models.DateTimeField(blank=True, help_text='When the AI roadmap was last generated', null=True)),
                ('target_completion_date', models.DateField(blank=True, help_text='Target date to achieve this goal', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the user started working on this goal', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the goal was completed', null=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority level (1=highest, 5=lowest)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this goal is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='profiles.userindustry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Learning Goal',
                'verbose_name_plural': 'User Learning Goals',
                'ordering': ['priority', '-created_at'],
                'unique_together': {('user', 'industry', 'skill_name')},
            },
        ),
    ]
