# Generated by Django 5.2.6 on 2025-09-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('role_selection', 'Role Selection'), ('basic_info', 'Basic Information'), ('industry_selection', 'Industry Selection'), ('goals_setup', 'Learning Goals Setup'), ('preferences', 'Preferences'), ('complete', 'Complete')], default='welcome', max_length=20),
        ),
    ]
