# Generated by Django 5.2.6 on 2025-10-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_update_onboarding_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(blank=True, help_text='Preferred learning style: hands_on, video, reading, mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time_commitment',
            field=models.CharField(blank=True, help_text='Weekly time commitment: 1-3, 3-5, 5-10, 10+', max_length=10),
        ),
    ]
