# Generated by Django 5.2.6 on 2025-10-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_learning_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transition_timeline',
            field=models.CharField(blank=True, help_text='Career transition timeline: immediate, 6_months, 1_year, long_term', max_length=15),
        ),
    ]
