# Generated by Django 5.2.6 on 2025-10-22 20:44

import helpers.generate_short_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_add_transition_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default=helpers.generate_short_id.generate_short_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
