# Generated by Django 5.2.6 on 2025-09-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_subscription_tier_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('learner', 'Learner'), ('professional', 'Professional'), ('mentor', 'Mentor'), ('hr_manager', 'HR Manager'), ('recruiter', 'Recruiter'), ('premium_user', 'Premium User'), ('vip_mentor', 'VIP Mentor')], help_text='User role - set during onboarding process', max_length=20, null=True),
        ),
    ]
