# Generated by Django 5.2.6 on 2025-11-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_make_role_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('new_user', 'New User'), ('super_admin', 'Super Admin'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('learner', 'Learner'), ('professional', 'Professional'), ('mentor', 'Mentor'), ('hr_manager', 'HR Manager'), ('recruiter', 'Recruiter'), ('premium_user', 'Premium User'), ('vip_mentor', 'VIP Mentor')], default='new_user', help_text='User role - defaults to new_user, updated during onboarding', max_length=20),
        ),
    ]
