"""
Request Key Validation for Azure Function Authentication

Provides secure validation of one-time request keys that Azure Functions
send back to Django for lesson generation.

Pattern: Similar to OTP (One-Time Password)
- Key is generated by Django when user triggers generation
- Key is passed to Azure Function via Service Bus message
- Azure Function includes key in request headers
- Django validates and deletes key (single-use only)
"""

import logging
from django.db import models
from django.utils import timezone
from .models import LessonGenerationRequest

logger = logging.getLogger(__name__)


class RequestKeyValidator:
    """Validates and manages one-time request keys for Azure Function authentication."""

    @staticmethod
    async def validate_request_key(request_key: str, user_id: str, module_id: str) -> bool:
        """
        Validate that a request key is valid and belongs to the user.

        Flow:
        1. Check key exists in database
        2. Check key hasn't been used
        3. Check key belongs to this user and module
        4. Delete key after validation (single-use pattern)

        Args:
            request_key: The one-time key from Azure Function headers
            user_id: User ID from GraphQL context
            module_id: Module ID being generated

        Returns:
            True if valid, False otherwise

        Raises:
            Exception with detailed error message if validation fails
        """
        try:
            # Try to find the request key
            from asgiref.sync import sync_to_async

            key_obj = await sync_to_async(
                LessonGenerationRequest.objects.filter(
                    request_key=request_key
                ).first
            )()

            if not key_obj:
                logger.warning(
                    f"🔑 [Validation] Request key not found or already used: {request_key[:10]}..."
                )
                raise Exception("Invalid or expired request key")

            # Validate key belongs to this user and module
            if str(key_obj.user_id) != str(user_id):
                logger.warning(
                    f"🔑 [Validation] Request key belongs to different user. "
                    f"Expected {user_id}, got {key_obj.user_id}"
                )
                raise Exception("Request key does not match user")

            if str(key_obj.module_id) != str(module_id):
                logger.warning(
                    f"🔑 [Validation] Request key belongs to different module. "
                    f"Expected {module_id}, got {key_obj.module_id}"
                )
                raise Exception("Request key does not match module")

            logger.info(
                f"✅ [Validation] Request key validated for user {user_id} and module {module_id}"
            )

            # Delete key (single-use pattern - like OTP after verification)
            await sync_to_async(key_obj.delete)()
            logger.info(f"🔑 [Validation] Request key deleted after validation (single-use)")

            return True

        except Exception as e:
            logger.error(f"❌ [Validation] Request key validation failed: {e}")
            raise

    @staticmethod
    def get_request_key_from_headers(request) -> str:
        """
        Extract request key from HTTP headers.

        Azure Function sends key in custom header: X-Request-Key

        Args:
            request: Django HTTP request object

        Returns:
            Request key string, or None if not found
        """
        # Django converts headers to META with HTTP_ prefix
        # X-Request-Key → HTTP_X_REQUEST_KEY
        request_key = request.META.get("HTTP_X_REQUEST_KEY", "").strip()

        if request_key:
            logger.debug(f"🔑 [Headers] Request key found in headers: {request_key[:10]}...")
            return request_key

        logger.debug(f"🔑 [Headers] No request key in headers")
        return None

    @staticmethod
    def get_user_id_from_headers(request) -> str:
        """
        Extract user ID from HTTP headers.

        Azure Function sends user ID in custom header: X-User-ID

        Args:
            request: Django HTTP request object

        Returns:
            User ID string, or None if not found
        """
        user_id = request.META.get("HTTP_X_USER_ID", "").strip()

        if user_id:
            logger.debug(f"👤 [Headers] User ID found in headers: {user_id}")
            return user_id

        logger.debug(f"👤 [Headers] No user ID in headers")
        return None

    @staticmethod
    def get_module_id_from_headers(request) -> str:
        """
        Extract module ID from HTTP headers.

        Azure Function sends module ID in custom header: X-Module-ID

        Args:
            request: Django HTTP request object

        Returns:
            Module ID string, or None if not found
        """
        module_id = request.META.get("HTTP_X_MODULE_ID", "").strip()

        if module_id:
            logger.debug(f"📦 [Headers] Module ID found in headers: {module_id}")
            return module_id

        logger.debug(f"📦 [Headers] No module ID in headers")
        return None
