# Generated by Django 5.2.6 on 2025-09-09 09:53

import django.db.models.deletion
import django.utils.timezone
import helpers.generate_short_id
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.CharField(default=helpers.generate_short_id.generate_short_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='Hashed OTP code for security', max_length=64)),
                ('purpose', models.CharField(choices=[('signin', 'Sign In'), ('signup', 'Sign Up'), ('password_reset', 'Password Reset'), ('device_verification', 'Device Verification')], default='signin', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of failed verification attempts')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum allowed verification attempts')),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'db_table': 'otp_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'expires_at'], name='otp_codes_user_id_fc10bf_idx'), models.Index(fields=['user', 'used_at'], name='otp_codes_user_id_f115fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPVerificationLink',
            fields=[
                ('id', models.CharField(default=helpers.generate_short_id.generate_short_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Secure verification token for email links', max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('signin', 'Sign In'), ('signup', 'Sign Up'), ('password_reset', 'Password Reset')], default='signin', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Link',
                'verbose_name_plural': 'Verification Links',
                'db_table': 'otp_verification_links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'expires_at'], name='otp_verific_user_id_4f9341_idx'), models.Index(fields=['token', 'purpose'], name='otp_verific_token_3cd933_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.CharField(default=helpers.generate_short_id.generate_short_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('device_fingerprint', models.CharField(help_text='Hashed device fingerprint (IP + User-Agent + other factors)', max_length=64)),
                ('device_name', models.CharField(help_text='Human-readable device name (e.g., Chrome on Windows)', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
                'db_table': 'trusted_devices',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['user', 'device_fingerprint'], name='trusted_dev_user_id_05a6cd_idx'), models.Index(fields=['user', 'is_active', 'last_used'], name='trusted_dev_user_id_423085_idx')],
                'unique_together': {('user', 'device_fingerprint')},
            },
        ),
    ]
