# Generated by Django 5.2.6 on 2025-10-08 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='created_by',
            field=models.CharField(db_index=True, default='gemini-ai', help_text="Content source: 'gemini-ai', 'openai', 'claude-ai', 'mentor:{user_id}', 'manual:{user_id}'", max_length=100),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='ai_model_version',
            field=models.CharField(default='gemini-1.5-flash', help_text="AI model version (e.g., 'gemini-1.5-flash', 'gpt-4', 'claude-3-opus', 'manual')", max_length=50),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when lesson was created/generated'),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered AI generation or created lesson manually', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='generation_prompt',
            field=models.TextField(blank=True, help_text='Prompt sent to AI (empty for manual creation)'),
        ),
    ]
