# Generated by Django 5.2.6 on 2025-10-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessoncontent_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='research_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Research metadata: time, sources count, quality metrics'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='source_attribution',
            field=models.JSONField(blank=True, default=dict, help_text='Research sources used (official docs, Stack Overflow, GitHub, Dev.to, YouTube)'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='source_type',
            field=models.CharField(choices=[('ai_only', 'AI-Generated Only'), ('multi_source', 'Multi-Source Research'), ('community_created', 'Community-Created'), ('mentor_created', 'Mentor-Created'), ('manual', 'Manually Created')], db_index=True, default='ai_only', help_text='Content generation method: AI-only vs multi-source research', max_length=50),
        ),
    ]
