# Generated by Django 5.2.6 on 2025-10-20 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_add_multi_source_research_attribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Module title (e.g., 'Python Basics')", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of module in roadmap')),
                ('estimated_duration', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('resources', models.JSONField(blank=True, default=list, help_text='Actual resource links used in lessons')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Community Approved'), ('rejected', 'Community Rejected'), ('mentor_verified', 'Mentor Verified')], db_index=True, default='pending', max_length=20)),
                ('cache_key', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['roadmap', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Roadmap title (e.g., 'Fullstack Python Developer')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Overview of the learning journey')),
                ('user_id', models.CharField(db_index=True, help_text='Reference to Django User.id', max_length=100)),
                ('goal_id', models.CharField(db_index=True, help_text='Reference to UserLearningGoal.id', max_length=100)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('total_duration', models.CharField(blank=True, help_text='Estimated completion time', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile_snapshot', models.JSONField(blank=True, default=dict, help_text='User context when generated')),
                ('ai_model_version', models.CharField(default='gemini-2.0-flash-exp', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('progress', models.JSONField(blank=True, default=dict, help_text='User progress tracking')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Community Approved'), ('rejected', 'Community Rejected'), ('mentor_verified', 'Mentor Verified')], db_index=True, default='pending', max_length=20)),
                ('cache_key', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Roadmap',
                'verbose_name_plural': 'Roadmaps',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Module this lesson belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='lessons.roadmap'),
        ),
    ]
