# Generated by Django 5.2.6 on 2025-10-20 23:56

import helpers.generate_short_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_module_roadmap_lessoncontent_module_module_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='id',
            field=models.CharField(default=helpers.generate_short_id.generate_short_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.CharField(default=helpers.generate_short_id.generate_short_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='id',
            field=models.CharField(default=helpers.generate_short_id.generate_short_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
