# Generated by Django 5.2.6 on 2025-10-21 20:15

import helpers.generate_short_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lessoncontent_id_alter_module_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='goal_input',
            field=models.CharField(default=1, help_text='Raw user goal input (used for caching and lookup)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonvote',
            name='id',
            field=models.CharField(default=helpers.generate_short_id.generate_short_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mentorreview',
            name='id',
            field=models.CharField(default=helpers.generate_short_id.generate_short_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='title',
            field=models.CharField(help_text="AI-generated roadmap title (e.g., 'Fullstack Python Developer')", max_length=255),
        ),
        migrations.AlterField(
            model_name='userroadmaplesson',
            name='id',
            field=models.CharField(default=helpers.generate_short_id.generate_short_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
