# Generated by Django 5.2.6 on 2025-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_roadmap_goal_input_alter_lessonvote_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=30),
        ),
        migrations.AlterField(
            model_name='module',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=30),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=30),
        ),
    ]
