# Generated by Django 5.2.6 on 2025-10-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lessoncontent_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='generation_completed_at',
            field=models.DateTimeField(blank=True, help_text='When generation job was completed', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='generation_error',
            field=models.TextField(blank=True, help_text='Error message if generation failed', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='generation_job_id',
            field=models.CharField(blank=True, help_text='Azure Durable Functions job ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='generation_started_at',
            field=models.DateTimeField(blank=True, help_text='When generation job was started', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='generation_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='not_started', help_text='Status of lesson generation process', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Prevents duplicate job submissions', max_length=64, null=True),
        ),
    ]
