# Generated by Django 5.2.6 on 2025-10-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_module_generation_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata about generation: prompt, system_prompt, model, temperature, generated_at, etc.'),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='ai_model_version',
            field=models.CharField(default='gemini-2.0-flash-exp', help_text="AI model version (e.g., 'gemini-2.0-flash-exp', 'gpt-4', 'claude-3-opus', 'manual')", max_length=50),
        ),
    ]
