# Generated by Django 5.2.6 on 2025-11-09 11:14

import helpers.generate_short_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_add_generation_metadata_jsonb'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonGenerationRequest',
            fields=[
                ('id', models.CharField(default=helpers.generate_short_id.generate_short_id, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('module_id', models.CharField(db_index=True, help_text='Module ID this key is for', max_length=10)),
                ('user_id', models.CharField(db_index=True, help_text='User ID who requested the generation', max_length=100)),
                ('request_key', models.CharField(db_index=True, help_text='Cryptographically secure unique key', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Lesson Generation Request',
                'verbose_name_plural': 'Lesson Generation Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_key'], name='lessons_les_request_1e84c4_idx'), models.Index(fields=['user_id', 'module_id'], name='lessons_les_user_id_787165_idx')],
            },
        ),
    ]
