# Generated by Django 5.2.6 on 2025-11-13 05:00

import django.core.validators
import helpers.generate_short_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_add_lesson_generation_request_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStructure',
            fields=[
                ('id', models.CharField(default=helpers.generate_short_id.generate_short_id, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('content_hash', models.CharField(db_index=True, help_text='MD5 hash of (module_title:difficulty:learning_pace:time_commitment)', max_length=64, unique=True)),
                ('module_title', models.CharField(db_index=True, help_text='Module title this structure is for', max_length=255)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, help_text='Module difficulty level', max_length=30)),
                ('learning_pace', models.CharField(choices=[('fast', 'Fast'), ('moderate', 'Moderate'), ('thorough', 'Thorough')], db_index=True, default='moderate', help_text="User's learning pace", max_length=20)),
                ('time_commitment_hours', models.FloatField(db_index=True, default=5.0, help_text="User's weekly time commitment (hours)")),
                ('structure', models.JSONField(help_text='List of lesson dicts with title, description, objectives, search_query, duration')),
                ('upvotes', models.IntegerField(default=0, help_text='Community upvotes on this structure', validators=[django.core.validators.MinValueValidator(0)])),
                ('downvotes', models.IntegerField(default=0, help_text='Community downvotes on this structure', validators=[django.core.validators.MinValueValidator(0)])),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Community Approved'), ('rejected', 'Community Rejected'), ('mentor_verified', 'Mentor Verified')], db_index=True, default='pending', help_text='Approval status (mentor_verified = most trusted)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this structure was first generated')),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, help_text='Last time this structure was used (for popularity tracking)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this record was updated')),
                ('generated_by_ai_model', models.CharField(default='gemini-2.0-flash-exp', help_text='AI model that generated this structure', max_length=50)),
            ],
            options={
                'verbose_name': 'Lesson Structure',
                'verbose_name_plural': 'Lesson Structures',
                'ordering': ['-last_used_at', '-created_at'],
                'indexes': [models.Index(fields=['content_hash'], name='lessons_les_content_4a158f_idx'), models.Index(fields=['module_title', 'difficulty', 'learning_pace'], name='lessons_les_module__611e07_idx'), models.Index(fields=['approval_status', '-upvotes'], name='lessons_les_approva_bf8eea_idx')],
            },
        ),
    ]
