# Generated by Django 5.2.6 on 2025-12-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_add_lesson_structure_caching'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='generation_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending Generation'),
                    ('generating', 'Currently Generating'),
                    ('completed', 'Generation Completed'),
                    ('failed', 'Generation Failed')
                ],
                db_index=True,
                default='completed',
                help_text='Status of lesson content generation',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='generation_error',
            field=models.TextField(
                blank=True,
                help_text='Error message if generation failed',
                null=True
            ),
        ),
    ]
